/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: ccd8c479fd854cefe110a3ffa0732700)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "MainDatabaseDO" | "EventsDatabaseDO";
	}
	interface Env {
		ASSETS: Fetcher;
		MAIN_DATABASE_DO: DurableObjectNamespace<import("./src/worker").MainDatabaseDO>;
		EVENTS_DATABASE_DO: DurableObjectNamespace<import("./src/worker").EventsDatabaseDO>;
	}
}
interface Env extends Cloudflare.Env {}
