// Ambient module declaration for the virtual module generated by the Vite plugin.
// Exports are DurableObject subclasses with names derived from database filenames
// (e.g. main.ts -> MainDatabaseDO).
declare module "virtual:eagerpatch/durable-db/__durableObjects";
