// Ambient module declarations for the virtual modules generated by the Vite plugin.

// Exports are DurableObject subclasses with names derived from database filenames
// (e.g. main.ts -> MainDatabaseDO).
declare module "virtual:durable-db/__durableObjects";

// Dev-epoch helpers baked in at build time. `applyDevEpoch` suffixes instance
// keys with the current dev epoch (identity in production builds).
declare module "virtual:durable-db/__devEpoch" {
  export const devEpoch: string | null;
  export function applyDevEpoch(key: string): string;
}

/** @deprecated Use "virtual:durable-db/__durableObjects" instead. */
declare module "virtual:eagerpatch/durable-db/__durableObjects";
