import type { DatabaseInfo, ActionInfo } from '../../db/types.js';
import { transformHandlerForDO, transformCrossDbCalls } from './parser.js';

/**
 * Options for code generation
 */
export interface GeneratorOptions {
  /** Import path for the context module */
  contextImport: string;
  /** Property path to get shop ID from context */
  shopIdPath: string;
}

/**
 * Context for cross-DB call transformation
 */
export interface CrossDbContext {
  /** Map of action name -> database info */
  actionToDatabase: Map<string, DatabaseInfo>;
}

/**
 * Generate RPC stub code for a database's actions
 *
 * This generates the code that users import and call.
 * Each action becomes an async function that:
 * 1. Gets context from AsyncLocalStorage
 * 2. Creates a DO stub using the appropriate ID strategy
 * 3. Calls the action method on the DO via RPC, passing instanceKey for cross-DB calls
 */
export function generateRpcStubs(
  database: DatabaseInfo,
  actions: ActionInfo[],
  options: GeneratorOptions
): string {
  const { contextImport, shopIdPath } = options;

  if (actions.length === 0) {
    return `// No actions defined for ${database.name}`;
  }

  const stubs = actions.map(action => {
    const instanceKey = database.instance === 'global'
      ? `'global'`
      : `ctx.${shopIdPath}`;

    const idStrategy = database.instance === 'global'
      ? `env.${database.bindingName}.idFromName('global')`
      : `env.${database.bindingName}.idFromName(ctx.${shopIdPath})`;

    return `
/**
 * ${action.exportName} action
 * @generated by @shoplayer/database
 */
export async function ${action.exportName}(args: Parameters<typeof import('${action.sourceFile}').${action.exportName}>[0]) {
  const ctx = getContext();
  const env = ctx.env;
  const id = ${idStrategy};
  const stub = env.${database.bindingName}.get(id);
  return stub.${action.exportName}(args, { instanceKey: ${instanceKey} });
}`;
  }).join('\n');

  return `import { getContext } from '${contextImport}';

${stubs}
`;
}

/**
 * Generate the Durable Object class for a database
 *
 * Creates a class that:
 * 1. Extends SqliteDurableObject
 * 2. Has migrations from the configured directory
 * 3. Has a method for each action that validates args and runs the handler
 * 4. Transforms internal action calls to this.actionName()
 * 5. Transforms cross-DB calls to proper RPC calls using ctx.env
 * 6. Receives instanceKey from RPC caller for cross-DB call key derivation
 */
export function generateDurableObjectClass(
  database: DatabaseInfo,
  actions: ActionInfo[],
  crossDbContext: CrossDbContext
): string {
  const methods = actions.map(action => {
    // Transform internal calls (same DB) to this.actionName()
    let transformedHandler = action.internalActionCalls.length > 0
      ? transformHandlerForDO(action.handlerSource, action.internalActionCalls)
      : action.handlerSource;

    // Transform cross-DB calls to proper RPC calls
    if (action.crossDbActionCalls.length > 0) {
      transformedHandler = transformCrossDbCalls(
        transformedHandler,
        action.crossDbActionCalls,
        crossDbContext.actionToDatabase
      );
    }

    const hasAnyCalls = action.internalActionCalls.length > 0 || action.crossDbActionCalls.length > 0;
    const commentSuffix = hasAnyCalls
      ? ` (${[
          action.internalActionCalls.length > 0 ? 'internal calls → this.*' : '',
          action.crossDbActionCalls.length > 0 ? 'cross-DB calls → RPC' : ''
        ].filter(Boolean).join(', ')})`
      : '';

    return `
  /**
   * ${action.exportName} action handler
   */
  async ${action.exportName}(args: unknown, rpcContext?: { instanceKey?: string }) {
    await this.ensureMigrations();
    
    // Validate args with ArkType
    const validator = type(${action.argsSchemaSource});
    const validated = validator(args);
    if (validated instanceof type.errors) {
      throw new Error(\`Invalid args for ${action.exportName}: \${validated.summary}\`);
    }
    
    // Create context for handler
    // - env: for cross-DO calls via ctx.env
    // - instanceKey: the key used to address this DO (for cross-DB per-shop calls)
    const ctx = { 
      env: this.env,
      instanceKey: rpcContext?.instanceKey ?? 'global'
    };
    
    // Execute handler${commentSuffix}
    const handler = ${transformedHandler};
    return handler(this.db, validated, ctx);
  }`;
  }).join('\n');

  // Generate migrations object
  const migrationsCode = generateMigrationsCode(database.migrations);

  return `
/**
 * ${database.className}
 * @generated by @shoplayer/database
 */
export class ${database.className} extends SqliteDurableObject {
  migrations = ${migrationsCode};
  ${methods}
}`;
}

/**
 * Generate the migrations object code from loaded migrations
 * Migrations are now chunk-based for breakpoint support
 */
function generateMigrationsCode(migrations?: Map<string, string[][]>): string {
  if (!migrations || migrations.size === 0) {
    return '{}';
  }

  const entries = Array.from(migrations.entries())
    .sort(([a], [b]) => a.localeCompare(b)) // Sort by migration name
    .map(([name, chunks]) => {
      // Generate chunks as arrays of statement arrays
      const chunksCode = chunks
        .map(chunk => {
          const statementsCode = chunk
            .map(s => JSON.stringify(s))
            .join(',\n          ');
          return `[\n          ${statementsCode}\n        ]`;
        })
        .join(',\n        ');

      return `    '${name}': {
      chunks: [
        ${chunksCode}
      ]
    }`;
    });

  return `{
${entries.join(',\n')}
  }`;
}

/**
 * Generate the complete Durable Objects module
 *
 * This creates a single module that exports all DO classes
 */
export function generateDurableObjectsModule(
  databases: DatabaseInfo[],
  actionsByDatabase: Map<string, ActionInfo[]>,
  allActions: ActionInfo[]
): string {
  // Build a map of action name -> database info for cross-DB call transformation
  const actionToDatabase = new Map<string, DatabaseInfo>();
  for (const db of databases) {
    const dbActions = actionsByDatabase.get(db.name) ?? [];
    for (const action of dbActions) {
      actionToDatabase.set(action.exportName, db);
    }
  }

  const crossDbContext: CrossDbContext = { actionToDatabase };

  const classes = databases.map(db => {
    const dbActions = actionsByDatabase.get(db.name) ?? [];
    return generateDurableObjectClass(db, dbActions, crossDbContext);
  }).join('\n');

  return `import { SqliteDurableObject } from '@shoplayer/database/db';
import { type } from 'arktype';

${classes}
`;
}

/**
 * Generate type definitions for the virtual modules
 */
export function generateTypeDefinitions(
  database: DatabaseInfo,
  actions: ActionInfo[]
): string {
  const actionTypes = actions.map(action => {
    return `export declare function ${action.exportName}(args: any): Promise<any>;`;
  }).join('\n');

  return `// Type definitions for shoplayer/databases/${database.name}
// @generated by @shoplayer/database

${actionTypes}
`;
}

/**
 * Generate the module that re-exports actions from the virtual module
 *
 * This transforms the user's database file to re-export from the generated stubs
 */
export function generateReExportModule(
  databaseName: string,
  actions: ActionInfo[]
): string {
  if (actions.length === 0) {
    return `// No actions to re-export`;
  }

  const names = actions.map(a => a.exportName).join(', ');
  return `export { ${names} } from 'shoplayer/databases/${databaseName}';`;
}
